### ISSUE TITLE
似乎存在一个不便：若发送图片，则不能自定义发送文本

### ISSUE THREAD

**Issue by Youkochan0v0** [Fndroid/tg_push_bot#2]
当url里有photo字段时，push到tg里的消息是图片+标题（图片链接）。也就是说目前的情况是只要有photo字段，text部分就是废的。
但从现实意义来讲，若同时有200字符以下的text字段，图片标题设定为这部分文本会比较合适；字符太多则另发一条新的文本信息。

**Comment by Fndroid** [comment]
@Youkochan0v0 你的问题是不能同时发图片加文字吗？如果是字符太多，你可以考虑分多个请求发送

**Comment by Youkochan0v0** [comment]
我测试的结果是不能同时发图片和文字，就是有图的话字会被吞掉

**Comment by Fndroid** [comment]
@Youkochan0v0 你发的图片不是https的，TG的接口不支持http的图片，所以我将http的图片当text处理了

**Comment by Youkochan0v0** [comment]
啊，的确是这样，那就没问题啦，谢谢~
