### ISSUE TITLE
怎么样才能推送到tg群?

### ISSUE THREAD

**Issue by shzxm** [Fndroid/tg_push_bot#7]
怎么样才能推送到tg群?
我试过在群里添加bot.但是无法获取到链接

**Comment by Fndroid** [comment]
不能

**Comment by LetMeDecay** [comment]
可以获取到链接的，不过好像改bot设置
个人用户的chatid是 `数字`，群组是 `-数字`，频道是 `@频道id`
加到群组之后你要进行权限判断，只有管理才能/start /end
